name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy NestJS App to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install Dependencies
      run: npm install

    - name: Build App
      run: npm run build

    - name: Upload Files to EC2
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "dist/*,package.json,ecosystem.config.js"
        target: "/home/${{ secrets.EC2_USER }}/nestjs-app"

    - name: SSH and Restart App
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/nestjs-app
          npm install --production
          pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
